### ISSUE TITLE
on_mqtt_message raised an Exception : Pas d'équipement avec l'id fourn

### ISSUE THREAD

**Issue by pirracas77** [BadWolf42/jMQTT#106] opened 2021-10-11 06:36 UTC
Hello:

I had a problem during last morning. The plugin stop to work.

Under which circunstancies could this error should arise?

`[2021-10-11 07:35:27][ERROR] : on_mqtt_message raised an Exception : Pas d'équipement avec l'id fourni (id=126)
[2021-10-11 07:35:27][ERROR] : on_mqtt_message raised an Exception : Pas d'équipement avec l'id fourni (id=126)
[2021-10-11 07:35:27][ERROR] : on_mqtt_message raised an Exception : Pas d'équipement avec l'id fourni (id=126)
[2021-10-11 07:35:27][ERROR] : on_mqtt_message raised an Exception : Pas d'équipement avec l'id fourni (id=126)
[2021-10-11 07:35:27][ERROR] : on_mqtt_message raised an Exception : Pas d'équipement avec l'id fourni (id=126)`

id=126 is the broker.

During this time, the plugin stopped to work. I solved it just stop/start it.

**Comment by Domochip** [comment] 2021-10-11 16:46
A friend of mine got this error, he restarted the daemon and it disappeared.
I need to investigate

**Comment by BadWolf42** [comment] 2021-11-02 15:18
Hi @pirracas77 , I was able to fully reproduce your issue!

Root cause is in the Core, the PR to fix and all the details are here: https://github.com/jeedom/core/pull/1882

Can you try to patch file `core/class/DB.class.php` and restart jMQTT daemon to validate?

Bad

**Comment by BadWolf42** [comment] 2021-11-03 09:10
PR has been merged in Alpha Core.

Did you check with the direct modification?

**Comment by pirracas77** [comment] 2021-11-03 14:08
> PR has been merged in Alpha Core.
> 
> Did you check with the direct modification?

Not yet

**Comment by BadWolf42** [comment] 2021-11-11 16:45
Fix has been merged in Beta Core since.

Did you check with the direct modification?

**Comment by BadWolf42** [comment] 2021-11-28 12:28
Hello @pirracas77, 
As PR has been merge in Jeedom Core (v4.2) alpha & beta, I will close this issue.
Is you still experience this issue in the future, feel free to open a new one.

**Closed as completed by BadWolf42** 2021-11-28 12:28 UTC
Labels: bug in core
